name             'setup_mysql'
maintainer       'OpenWorks'
maintainer_email 'sei.emoto@gmail.com'
license          'All rights reserved'
description      'Installs/Configures setup_mysql'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'mysql'
#depends          'mysql2_chef_gem'
#depends          'database'
